# Generated by Django 6.0.6 on 2026-07-30 09:30

import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_message_audio_file_message_duration_seconds_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='audio_file',
            field=models.FileField(blank=True, null=True, storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(), upload_to='voice_messages/'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to='profile_pics/'),
        ),
    ]
